const QUOTES = [
  { text: "You do not yield.", author: "Sarah J. Maas" },
  { text: "Sometimes to self-discover, you must self-destruct.", author: "Robert M. Drake" },
  { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
  { text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
  { text: "Every morning you have two choices: continue to sleep with your dreams, or wake up and chase them.", author: "Unknown" },
  { text: "A river cuts through rock not because of its power but because of its persistence.", author: "Unknown" },
  { text: "Success is not final, failure is not fatal; it is the courage to continue that counts.", author: "Winston Churchill" },
  { text: "Don't stop until you're proud.", author: "Unknown" },
  { text: "Work as hard as you can and then be happy in the knowledge you couldn’t have done any more.", author: "Unknown" },
  { text: "You may see me struggle, but you will never see me quit.", author: "Unknown" },
  { text: "Work hard in silence. Let success make the noise.", author: "Unknown" },
  { text: "Be stronger than your excuses.", author: "Unknown" },
  { text: "Be so good they can’t ignore you.", author: "Unknown" },
  { text: "You have three choices: give up, give in or give it everything you have got.", author: "Unknown" },
  { text: "Successful people are not gifted. They just work hard, then succeed on purpose.", author: "Unknown" },
  { text: "Never let small minds convince you that your dreams are too big.", author: "Unknown" },
  { text: "The people who are crazy enough to believe they can change the world are the ones who do.", author: "Steve Jobs" },
  { text: "Productivity is about looking forward. Looking back too much, or trying to be too much of a perfectionist, can destroy that productivity. So keep going. Keep creating. Keep building.", author: "Unknown" },
  { text: "Hard work beats talent when talent doesn’t work hard.", author: "Unknown" },
  { text: "Impossible is not a fact. It is an opinion.", author: "Unknown" },
  { text: "Too many people overvalue what they are not and undervalue what they are.", author: "Unknown" },
  { text: "You don’t learn to walk by following rules. You learn by doing, and by falling over.", author: "Richard Branson" },
  { text: "More people would learn from their mistakes if they weren’t so busy denying them.", author: "Harold J. Smith" },
  { text: "Learn from yesterday. Live for today. Hope for tomorrow.", author: "Albert Einstein" },
  { text: "Don’t let the fear of failure be greater than the excitement of success.", author: "Unknown" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "FEAR – Forget Everything And Run… or… Face Everything And Rise. It’s your choice.", author: "Unknown" },
  { text: "In the end, we only regret the chances we didn’t take.", author: "Unknown" },
  { text: "Nothing you do now can change the past. But I promise you, everything you do now will determine your future.", author: "Unknown" },
  { text: "Our greatest glory is not in never failing, but in rising every time we fail.", author: "Confucius" },
  { text: "Anytime someone tells me that I can't do something, I want to do it more.", author: "Taylor Swift" },
  { text: "In the End, we will remember not the words of our enemies, but the silence of our friends.", author: "Martin Luther King, Jr." },
  { text: "If you are lucky enough to find something that you love, and you have a shot at being good at it, don't stop, don't put it down", author: "Taylor Swift" },
  { text: "You are not the opinion of someone who doesn’t know you.", author: "Taylor Swift" },
  { text: "Never be ashamed of trying. Effortlessness is a myth.", author: "Taylor Swift" },
  { text: "The people who are the most successful in this world are the ones who don’t stop asking questions, who don’t stop being curious, and who don’t stop searching for the truth.", author: "Taylor Swift" },
  { text: "Never believe anyone who tells you that you don’t deserve what you want.", author: "Taylor Swift" },
  { text: "In life and love, you learn that there comes a time to let go and move on.", author: "Taylor Swift" },
  { text: "People are going to judge you anyway, so you might as well do what you want.", author: "Taylor Swift" },
  { text: "So make the friendship bracelets, take the moment and taste it.", author: "Taylor Swift" },
  { text: "You can be accidentally successful for three or four years. Accidents happen. But careers take hard work.", author: "Taylor Swift" },
  { text: "FEARLESS is getting back up and fighting for what you want over and over again even though every time you’ve tried before you’ve lost.", author: "Taylor Swift" },
  { text: "If you’re being met with resistance, that probably means you’re doing something new. If you’re experiencing turbulence or pressure, that probably means you’re rising.", author: "Taylor Swift" },
  { text: "Being fearless isn’t being 100 percent not fearful; it’s being terrified but you jump anyway.", author: "Taylor Swift" },
  { text: "If somebody hurts you, it’s okay to cry a river, just remember to build a bridge and get over it.", author: "Taylor Swift" },
  { text: "I still think it’s important to be polite, but not at all costs. Not when you’re being pushed beyond your limits, and not when people are walking all over you.", author: "Taylor Swift" },
  { text: "Grow a backbone, trust your gut, and know when to strike back. Be like a snake – only bite if someone steps on you.", author: "Taylor Swift" },
  { text: "I’ve come to a realization that I need to be able to forgive myself for making the wrong choice, trusting the wrong person, or figuratively falling on my face in front of everyone.", author: "Taylor Swift" },
  { text: "I’ve never been a natural. All I do is try, try, try.", author: "Taylor Swift" },
  { text: "People throw rocks at things that shine.", author: "Taylor Swift" },
  { text: "And if you never bleed, you’re never gonna grow.", author: "Taylor Swift" },
  { text: "Everything you lose is a step you take.", author: "Taylor Swift" },
  { text: "Step into the daylight, and let it go.", author: "Taylor Swift" },
  { text: "You can walk away and say 'We don't need this.' but something in your eyes says 'We can beat this.'", author: "Taylor Swift" },
  { text: "It's going to happen because I'm going to MAKE it happen.", author: "Taylor Swift" },
  { text: "I passed the pictures around of all the years that we stood there on the sidelines wishing for right now.", author: "Taylor Swift" },
  { text: "You've got no reason to be afraid. You're on your own kid, yeah you can face this.", author: "Taylor Swift" },
  { text: "Long story short, I survived.", author: "Taylor Swift" },
  { text: "They've got my past, frozen behind glass, but I've got me.", author: "Taylor Swift" },
  { text: "Today is never too late to be brand new.", author: "Taylor Swift" },
  { text: "I got smarter, I got harder in the nick of time.", author: "Taylor Swift" },
  { text: "Honey, I rose up from the dead, I do it all the time.", author: "Taylor Swift" },
  { text: "Dear Reader, you don't have to answer just cause they asked you.", author: "Taylor Swift" },
  { text: "If the shoe fits, walk in it 'til your high heels break.", author: "Taylor Swift" },
  { text: "Past me, I wanna tell you not to get lost in these petty things. Your nemeses, will defeat themselves before you get the chance to swing.", author: "Taylor Swift" },
  { text: "What's a girl gonna do? A diamond's gotta shine!", author: "Taylor Swift" },
  { text: "Dear Reader, bend when you can, snap when you have to.", author: "Taylor Swift" },
  { text: "Who you are is not where you’ve been. You’re still an innocent.", author: "Taylor Swift" },
  { text: "I miss you, but I miss SPARKLING!", author: "Taylor Swift" },
  { text: "I can reclaim the land!", author: "Taylor Swift" },
  { text: "To live for the hope of it all.", author: "Taylor Swift" }
   
  
  
  /** { text: "", author: "" }, **/
];
